### ISSUE TITLE
Review of migration from SourceForge

### ISSUE THREAD

**Issue by hlapp** [evoinfo/cdao#1]
@balhoff @arlin @epontell @rvosa if you don't mind could you take a moment and check the state and files in this repo for whether it is a faithful migration of the [CDAO repository on SourceForge](https://sourceforge.net/projects/cdao/)?

**Comment by hlapp** [comment]
Note that I left the svn-id metadata in the commit messages on purpose. If left out (which is an option) then it'll be very difficult or impossible to resolve any previous references to particular versions in subversion.

**Comment by hlapp** [comment]
@balhoff as the CDAO maintainer currently on record, could you please take a look and indicate approval or provide comments on actual or potential issues?

**Comment by balhoff** [comment]
I think this looks good; I don't see any issues. We should update https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/cdao.yml to point here.

**Comment by balhoff** [comment]
Actually I take it back, we're not quite ready to point the release here. The CDAO releases are housed in the OBO SVN here: http://svn.code.sf.net/p/obo/svn/ontologies/trunk/CDAO/

**Comment by hlapp** [comment]
> The CDAO releases are housed in the OBO SVN here: http://svn.code.sf.net/p/obo/svn/ontologies/trunk/CDAO/

I was hoping we could use Github release tags for that. Can't we state the expansion of versioned releases differently from the unversioned ontology?

**Comment by balhoff** [comment]
Yes, we can use release tags. Here's an example: https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/taxrank.yml

**Comment by epontell** [comment]
Looks ok to me.

 

Enrico

**Comment by hlapp** [comment]
The SourceForge repo actually has two version control repositories. The second (and older) one that isn't included in this migration is the CVS repository. Please see #3 for the results and discussion of that.

**Comment by hlapp** [comment]
See #4 for review of release tag porting.

**Comment by hlapp** [comment]
With the completion of #3 and #4 I think we can call this complete now, too. See #5 for the remaining task of updating the OBO metadata record.
