### ISSUE TITLE
Review CDAO release tags

### ISSUE THREAD

**Issue by hlapp** [evoinfo/cdao#4]
I created 4 tags (to be promoted to release tags) for the history of CDAO releases:
* [cdao-rel-2013-02-01](https://github.com/evoinfo/cdao/releases/tag/cdao-rel-2013-02-01)
* [cdao-rel-2012-06-06](https://github.com/evoinfo/cdao/releases/tag/cdao-rel-2012-06-06)
* [cdao-rel-2012-04-12](https://github.com/evoinfo/cdao/releases/tag/cdao-rel-2012-04-12)
* [cdao-rel-1.0](https://github.com/evoinfo/cdao/releases/tag/cdao-rel-1.0)

Once I promote them to releases I can't delete them anymore, hence @balhoff @epontell @arlin could you please review for accuracy etc and give 👍 or 👎 ?

BTW I notice that URLs and commit SHA1s in the tag's comments aren't hyperlinked in the per-tag pages linked to above. They are, however, in the [list of tags](https://github.com/evoinfo/cdao/tags); simply click the `...` dots to expand the description.

**Comment by hlapp** [comment]
@balhoff any chance you can give this a second pair of eyes so I can go ahead and create releases?

**Comment by balhoff** [comment]
It looks like the version IRIs match up for the dated releases. I guess 1.0 will just need to be a tag and not redirect from a version IRI, since it didn't have one. Looks good to me.

**Comment by hlapp** [comment]
All promoted to releases now.

Note that I had to retag the [2013-02-01 release tag](https://github.com/evoinfo/cdao/releases/tag/cdao-rel-2013-02-01) so that they show up in the correct order, and that the "latest release" is correctly pointing to the 2013-02-01 release. If anyone has the repo cloned or forked, you will need to force-update that tag, or re-clone/re-fork.
